### ISSUE TITLE
omprs-linux-x86 contains a x86_64 build

### ISSUE THREAD

**Issue by 0x617374726F** [Sreyas-Sreelal/omprs#1]
When downloading the [latest linux-x86 build](https://github.com/Sreyas-Sreelal/omprs/releases/download/1.1.0/omprs-linux-x86-1.1.0.zip), I figured out that it actually contains a 64 bit library. Also, it is archived as a zip as well as a tar.xz, which is kind of confusing.

**Comment by 0x617374726F** [comment]
I was able to build it myself with Docker. I built the image using:

```
FROM debian:12

RUN dpkg --add-architecture i386 && \
  apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y ninja-build clang pipx python3-setuptools python3-wheel \
    libstdc++6-i386-cross libc6 libc6-i386 git build-essential g++-multilib gcc-multilib \
    libc6-dev-i386 libstdc++6:i386 cmake pkg-config wget curl
RUN pipx install conan==1.65.0
RUN git clone --recursive https://github.com/Sreyas-Sreelal/omprs
ENV PATH $PATH:/root/.local/bin
RUN cd ./omprs && \
  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_CXX_STANDARD=17 -S . -B build -G Ninja
RUN cd ./omprs && cmake --build build
```

Extracted the library by bind mounting to the host and copying to the mounted directory.

**Comment by Sreyas-Sreelal** [comment]
Thank you. I've updated x86 release, it should be working now.
